sudo: required

language: python

services:
  - docker

before_install:
  - docker build -f Dockerfile-test -t oofn/pyspark .

install:
  pip3 install --no-cache-dir -r requirements.txt

script:
  py.test -s -v
