version: "3"
services:
    #hbase:
    #    build: ./hbase-docker
    #    ports:
    #    - "2181:2181"
    #    - "60000:60000"
    #    - "60010:60010"
    #    - "60020:60020"
    #    - "60030:60030"
    node:
        build: 
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www